import { Figtree } from "next/font/google";
import "./bulma.min.css";
import { Navbar } from "./HeaderUnit";
import { cookies } from "next/headers";
import { decrypt } from "@/app/cookieUtilities";

const figtree = Figtree({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "NWC Finance Thing",
  description: "Generated by create next app",
};

const RootLayout = async ({ children }) => {
  const cookieStore = await cookies();
  const sessionCookie = cookieStore.get("session");
  return (
    <html lang="en" data-theme="light">
      <body className={figtree.className}>
        <header className="header">
          <Navbar loggedIn={sessionCookie ? true : false} />
        </header>
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
